### ISSUE TITLE
Agregar paquetes para la capa service.

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#141]
Agregue a la estructura del proyecto los nuevos paquetes para implementar la capa service de la 
aplicación.

**Comment by Evelin-Rocha** [comment]
Los paquetes han sido creados. Ya pueden trabajar en la capa service.
[Creacion_capa_service] (https://github.com/FernandoValero/TrabajoPracticoN2/tree/Creacion_capa_service)

**Comment by Evelin-Rocha** [comment]
Tarea terminada, todos los cambios están en la rama:

[Creacion_capa_service](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Creacion_capa_service)

**Comment by DavidS-Martinez** [comment]
Mensaje recibido
