### ISSUE TITLE
Documentación de código paquete service (Servicios).

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#146]
Documentación interna del código en el paquete service.

**Comment by NestorCorimayo** [comment]
Se crearon las interfaces, se hizo la declaración de métodos y se aplico la inyección de dependencia.
Se adjunta link de rama en la que se trabajo.
tp2_Grupo24/src/main/java/ar/edu/unju/fi/service/IServicioService.java

**Comment by DavidS-Martinez** [comment]
[nombre de la rama](Ruta de la rama)
