### ISSUE TITLE
Implementación de la capa service (consejos)

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#148]
En el paquete service crear la interfaz necesaria para declarar los métodos.
La declaración de métodos abstractos dentro de las interfaces deben permitir implementar en las clases de 
service.imp las siguientes acciones: 
Listar, guardar, modificar, eliminar, buscar (por algún criterio), recuperar un objeto del model.

En el paquete service.imp cree las clases que implementen las interfaces.

En las clases del paquete controller y service.imp aplique la inyección de dependencia utilizando la 
anotación @Autowired.

**Comment by Evelin-Rocha** [comment]
[creacion_interfaz_y_clase_de_consejo](https://github.com/FernandoValero/TrabajoPracticoN2/tree/documentacion_codigo_paquete_service_consejo)
