### ISSUE TITLE
Implementación de la capa service (Productos)

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#149]
En el paquete service crear la interfaz necesaria para declarar los métodos.
La declaración de métodos abstractos dentro de las interfaces deben permitir implementar en las clases de 
service.imp las siguientes acciones: 
Listar, guardar, modificar, eliminar, buscar (por algún criterio), recuperar un objeto del model.

En el paquete service.imp cree las clases que implementen las interfaces.

En las clases del paquete controller y service.imp aplique la inyección de dependencia utilizando la 
anotación @Autowired.

**Comment by DavidS-Martinez** [comment]
Se Finalizó la implementación de la capa servicio en Producto. Si hay errores me hacen saber (me sirve la retroalimentación).

[Capa_Servicio_Producto](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Capa_Servicio_Producto)
