### ISSUE TITLE
Agregue en el archivo application.properties las propiedades necesarias y modificar el nombre del paquete model.

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#164]
Agregue en el archivo application.properties las propiedades necesarias para el acceso y configuración 
de base de datos. 

Ejemplo para mysql:
spring.datasource.url=jdbc:mysql://localhost:3306/bdejemplo2023?serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto =create-drop

Modificar el nombre de paquete model a entity. R

**Comment by DavidS-Martinez** [comment]
Ahora lo hago

**Comment by DavidS-Martinez** [comment]
Detalle a destacar que faltó hacer el pull por eso quedó así la rama.

Archivo application.properties configurado para trabajo con Base de Datos MySql

[Configuración_del_archivo_properties](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Configuraci%C3%B3n_del_archivo_properties)

**Comment by DavidS-Martinez** [comment]
Modificación del paquete model a entity realizado

[Modificación_del_paquete_model](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Modificaci%C3%B3n_del_paquete_model)
[Adaptar_import_para_el_nuevo_paquete](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Adaptar_import_para_el_nuevo_paquete)
[]Reparación_del_error_de_entity(https://github.com/FernandoValero/TrabajoPracticoN2/tree/Reparaci%C3%B3n_del_error_de_entity)

**Comment by DavidS-Martinez** [comment]
Se modificó el nombre de la BBDD
[Cambio_de_nombre_de_BBDD](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Cambio_de_nombre_de_BBDD)
