### ISSUE TITLE
Modificación de paquete entity, productos

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#165]
* Realizar el mapeo utilizando anotaciones pertenecientes al paquete jakarta.persistence (@Entity, @Table, @Id, @Column, @OneToMany, @OneToOne etc.) 
* En cada clase se debe indicar que atributo será la clave primaria (@Id), agregar un atributo de tipo Long con nombre id.
* Por cada atributo indicar el nombre de la columna (@Column).

**Comment by DavidS-Martinez** [comment]
Trabajo Terminado

Se tomo como atributo clave id en vez de código

[Mapeo_del_Producto_con_jakarta.persistence](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Mapeo_del_Producto_con_jakarta.persistence)

**Comment by DavidS-Martinez** [comment]
Corrección del archivo nuevo_producto.html para que permita al usuario modificar un Producto

[Correción_de_error_al_momento_de_editar](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Correci%C3%B3n_de_error_al_momento_de_editar)
