### ISSUE TITLE
Modificación de paquete entity, consejos.

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#166]
* Realizar el mapeo utilizando anotaciones pertenecientes al paquete jakarta.persistence (@Entity, @Table, @Id, @Column, @OneToMany, @OneToOne etc.) 
* En cada clase se debe indicar que atributo será la clave primaria (@Id), agregar un atributo de tipo Long con nombre id.
* Por cada atributo indicar el nombre de la columna (@Column).

**Comment by Evelin-Rocha** [comment]
Se modificó el paquete entity para consejos.
[modificacion_paquete_entity_consejos](https://github.com/FernandoValero/TrabajoPracticoN2/tree/modificacion_paquete_entity_consejos)

**Comment by FernandoValero** [comment]
Se corrigió el error al modificar un dato de la BD.
Rama en la que se trabajo [correccion_error_modificacion_consejos](https://github.com/FernandoValero/TrabajoPracticoN2/tree/correccion_error_modificacion_consejo)
