### ISSUE TITLE
Modificación de paquete entity, servicios.

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#167]
* Realizar el mapeo utilizando anotaciones pertenecientes al paquete jakarta.persistence (@Entity, @Table, @Id, @Column, @OneToMany, @OneToOne etc.) 
* En cada clase se debe indicar que atributo será la clave primaria (@Id), agregar un atributo de tipo Long con nombre id.
* Por cada atributo indicar el nombre de la columna (@Column).

**Comment by NestorCorimayo** [comment]
ok

**Comment by NestorCorimayo** [comment]
Se finalizo con la implementación necesaria para hacer uso de una BD.
[Modificación_de_paquete_entity_servicios](https://github.com/users/FernandoValero/projects/1?pane=issue&itemId=31038029)
