### ISSUE TITLE
Documentación de código, productos.

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#169]
Continuar con la documentación interna de código.

**Comment by DavidS-Martinez** [comment]
Documentación realizada a: ProductoServiceMysqulImp y IProductoRepository
[Documentación_de_código_producto](https://github.com/FernandoValero/TrabajoPracticoN2/tree/Documentaci%C3%B3n_de_c%C3%B3digo_producto)
