### ISSUE TITLE
Documentación de código, servicios. 

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/TrabajoPracticoN2#182]
Continuar con la documentación interna de código.

**Comment by NestorCorimayo** [comment]
okey compañero.... dentro de muy pronto estará listo esta issue

**Comment by NestorCorimayo** [comment]
Se ha finalizado la documentacion interna del codigo en Servicios:
[Documentacion_de_codigo_Servicio](https://github.com/FernandoValero/TrabajoPracticoN2/compare/Documentacion_de_codigo_Servicio?expand=1)

**Comment by NestorCorimayo** [comment]
Se ha corregido servicio.html y nuevo_servicio.html para su correcta ejecución.
 [Correccion_en_Servicio](https://github.com/FernandoValero/TrabajoPracticoN2/pull/190)
